import os
import struct
import json
import time
import threading
import warnings
import shutil
from datetime import datetime, timezone
from typing import Any, Optional, Callable, Dict, List
from pathlib import Path
import msgpack
import uuid
import base64
import requests
from importlib.metadata import version, PackageNotFoundError

from .channel import ChannelDef
from .serialize import get_or_make_handler
from .serialize import resolve_value
from .sync import ChunkSyncer, BackgroundSyncThread

# function localization for commonly used paths
_pack_uint32 = struct.Struct("<I").pack
_msgpack_packb = msgpack.packb
_time_ns = time.time_ns

class LabLog:
    trial_name: str # name of trial
    experiment_id: str # grouping for trial
    researcher: str # person running trial
    hostname: str # machine name
    server: str # server, wip
    run_id: str # unique id for this run, generated by client
    run_path: Path
    channels: Dict[str, ChannelDef]
    # channel tiers
    # 1. float, int, ndarray, Tensor
    # 2. string, dict, list, model weights
    # 3. JSON version of a device.
    
    _GLOBAL_CONFIG = {
        "auto_recover_orphans": os.getenv("LABLOG_AUTO_RECOVER", "false").lower() == "true",
        "cache_dir": os.getenv("LABLOG_CACHE_DIR", "~/.lablog/cache")
    }

    @staticmethod
    def configure_global(auto_recover_orphans: Optional[bool] = None, cache_dir: Optional[str] = None):
        if auto_recover_orphans is not None:
            LabLog._GLOBAL_CONFIG["auto_recover_orphans"] = auto_recover_orphans
        if cache_dir is not None:
            LabLog._GLOBAL_CONFIG["cache_dir"] = cache_dir

    @staticmethod
    def find_orphaned_runs() -> List[Dict[str, Any]]:
        cache_root = Path(LabLog._GLOBAL_CONFIG["cache_dir"]).expanduser()
        if not cache_root.exists():
            return []
        
        orphans = []
        # ~/.lablog/cache/<experiment_id>/<run_id>/
        for exp_dir in cache_root.iterdir():
            if not exp_dir.is_dir():
                continue
            for run_dir in exp_dir.iterdir():
                if not run_dir.is_dir():
                    continue
                
                manifest_path = run_dir / "manifest.json"
                active_path = run_dir / ".active"
                if manifest_path.exists() and not active_path.exists():
                    try:
                        with open(manifest_path, "r") as f:
                            manifest = json.load(f)
                        # currently making any thing in the cache be an orphan if it not the active path.
                        orphans.append({
                            "run_id": manifest.get("run_id"),
                            "experiment_id": manifest.get("experiment_id"),
                            "trial_name": manifest.get("trial_name"),
                            "last_modified": datetime.fromtimestamp(run_dir.stat().st_mtime, tz=timezone.utc),
                            "status": "incomplete",
                            "path": run_dir
                        })
                    except Exception:
                        continue
        return orphans

    @staticmethod
    def finalize_orphan(run_id: str, server: str = "localhost:36524", ssl_verify: bool | str = True):
        orphans = LabLog.find_orphaned_runs()
        orphan = next((o for o in orphans if o["run_id"] == run_id), None)
        if not orphan:
            warnings.warn(f"Orphaned run {run_id} not found")
            return

        run_path = orphan["path"]
        syncer = ChunkSyncer(run_path, run_id, server, ssl_verify=ssl_verify)
        syncer.sync_pending()
        
        # determine last chunk index
        chunk_files = list((run_path / "chunks").glob("*.bin"))
        if chunk_files:
            final_idx = max(int(p.stem) for p in chunk_files)
        else:
            final_idx = -1
            
        res = syncer.complete(final_idx)
        if res:
            shutil.rmtree(run_path)
            return True
        return False

    @staticmethod
    def discard_orphan(run_id: str):
        orphans = LabLog.find_orphaned_runs()
        orphan = next((o for o in orphans if o["run_id"] == run_id), None)
        if orphan:
            shutil.rmtree(orphan["path"])
            return True
        return False

    config: Dict[str, Any]
    _lock: threading.Lock
    _log_file: Optional[Any] = None
    _log_file_count: int = 0
    _current_log_size: int = 0
    
    timestamp_start: datetime # all times in utc
            
    def __init__(self, 
                 trial_name: str, 
                 experiment_id: str, 
                 researcher: str = "", 
                 hostname: str = "", 
                 server: str = "localhost:36524",
                 cache_dir: Optional[str] = None,
                 ssl_verify: bool | str = False):
        """LabLog object, contains everything to run client, declare channels, and sync data with server

        Args:
            trial_name (str): Descriptive name of this trial/run, e.g. "lr=0.01, batch=32"
            experiment_id (str): Name for group of related trials.
            researcher (str, optional): Researcher name. Defaults to "".
            hostname (str, optional): Computer. Defaults to "".
            server (_type_, optional): IP:port address. Defaults to "localhost:36524".
            cache_dir (Optional[str], optional): Where to save files. Defaults to ~/.lablog/cache.
            ssl_verify (bool | str, optional): Either provide a path to a server cert "certs/server_cert.pem" or leave as false. Defaults to False.
        """        
        self.trial_name = trial_name
        self.experiment_id = experiment_id
        self.researcher = researcher
        self.hostname = hostname
        self.server = server
        self.ssl_verify = ssl_verify
        self.run_id = self._generate_short_uuid()
        self.timestamp_start = datetime.now(timezone.utc)
        self.channels = {}
        self._lock = threading.Lock()
        self._log_file_count = 0
        self._current_log_size = 0
        self.trial_number = 0
        
        effective_cache_dir = cache_dir or LabLog._GLOBAL_CONFIG["cache_dir"]
        self.config = {
            "sync_interval": 30,
            "chunk_size_mb": 32,
            "non_loggable_params": {},
            "cache_dir": effective_cache_dir
        }

        # cache_dir/<experiment_id>/<run_id>/
        self.run_path = Path(self.config["cache_dir"]).expanduser() / self.experiment_id / self.run_id
        self.run_path.mkdir(parents=True, exist_ok=True)
        (self.run_path / "chunks").mkdir(exist_ok=True)

        # locking system
        self._lock_file_path = self.run_path / ".active"
        self._lock_file_path.touch()

        if LabLog._GLOBAL_CONFIG["auto_recover_orphans"]:
            self._recover_orphans()

        self._init_sync_state()
        self._write_manifest()
        self._send_manifest()

        self._syncer = ChunkSyncer(self.run_path, self.run_id, self.server,
                                   ssl_verify=self.ssl_verify)
        self._bg_sync: Optional[BackgroundSyncThread] = None
        if self.config["sync_interval"] > 0:
            self._bg_sync = BackgroundSyncThread(self._sync_internal, self.config["sync_interval"])
            self._bg_sync.start()

    def _recover_orphans(self):
        orphans = LabLog.find_orphaned_runs()
        for orphan in orphans:
            if orphan["run_id"] == self.run_id:
                continue
            try:
                LabLog.finalize_orphan(orphan["run_id"], self.server, ssl_verify=self.ssl_verify)
            except Exception as e:
                warnings.warn(f"Failed to auto-recover orphan {orphan['run_id']}: {e}")

    def _init_sync_state(self):
        state_path = self.run_path / "sync_state.json"
        state = {
            "confirmed_chunks": [],
            "pending_chunks": [],
            "total_frames_written": 0
        }
        with open(state_path, "w") as f:
            json.dump(state, f, indent=2)

    def _send_manifest(self) -> bool:
        url = f"https://{self.server}/runs"
        try:
            response = requests.post(url, json=self._generate_manifest(), timeout=0.5, verify=self.ssl_verify)
            if response.status_code in (200, 201):
                data = response.json()
                self.trial_number = data.get("trial_number", 0)
                self._write_manifest(sync_to_server=False)
                return True
            else:
                warnings.warn(f"Server rejected manifest with status {response.status_code}. Continuing locally.")
                return False
        except Exception as e:
            warnings.warn(f"Failed to reach server {self.server}: {e}. Continuing locally.")
            return False

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        status = "complete" if exc_type is None else "incomplete"
        self.complete(status=status)

    def configure(self, 
                  sync_interval: Optional[int] = None, 
                  chunk_size_mb: Optional[float] = None, 
                  non_loggable_params: Optional[dict] = None, 
                  server: Optional[str] = None):
        
        if sync_interval is not None: self.config["sync_interval"] = sync_interval
        if chunk_size_mb is not None: self.config["chunk_size_mb"] = chunk_size_mb
        if non_loggable_params is not None: self.config["non_loggable_params"] = non_loggable_params
        if server is not None: self.server = server
        
        # sync reset
        if sync_interval is not None:
            if self._bg_sync is not None:
                self._bg_sync.stop()
                self._bg_sync = None
            if self.config["sync_interval"] > 0:
                self._bg_sync = BackgroundSyncThread(self._sync_internal, self.config["sync_interval"])
                self._bg_sync.start()

        self._write_manifest(sync_to_server=True)

    def _write_manifest(self, sync_to_server: bool = True):
        manifest_path = self.run_path / "manifest.json"
        manifest_data = self._generate_manifest()
        with open(manifest_path, "w") as f:
            json.dump(manifest_data, f, indent=2)
            
        if sync_to_server and getattr(self, "server", None):
            try:
                # Use a short timeout so logging doesn't block heavily
                requests.post(f"https://{self.server}/runs", json=manifest_data, timeout=0.2, verify=self.ssl_verify)
            except Exception:
                pass

    def declare_channel(self, 
                        name: str, 
                        dtype: str, 
                        shape: Optional[List[Optional[int]]] = None, 
                        unit: Optional[str] = None,
                        description: Optional[str] = None,
                        compression: str = "gzip",
                        compression_level: int = 4,
                        frequency_hz: Optional[float] = None,
                        serializer: Optional[Callable[[Any], Any]] = None,
                        pickle: bool = False):
        
        ch = ChannelDef(
            name=name,
            dtype=dtype,
            shape=shape,
            unit=unit,
            description=description,
            compression=compression,
            compression_level=compression_level,
            frequency_hz=frequency_hz,
            serializer=serializer,
            pickle=pickle
        )
        ch.validate()
        self.channels[name] = ch
        self._write_manifest(sync_to_server=True)

    def log(self, channel_name: str, value: Any, timestamp: Optional[int] = None):
        # now using hashtable, much faster lookups.
        ch = self.channels.get(channel_name)
        if ch is None:
            warnings.warn(f"Ad-hoc logging to undeclared channel '{channel_name}'")
            resolved_dtype, _ = resolve_value(None, value)
            ch = ChannelDef(name=channel_name, dtype=resolved_dtype)
            self.channels[channel_name] = ch
            self._write_manifest(sync_to_server=True)

        # save used handler
        if ch._cached_handler is None:
            ch._cached_handler = get_or_make_handler(ch, value)
        
        ts_ns = timestamp if timestamp is not None else _time_ns()
        
        _, serialized_value = ch._cached_handler(value)
        
        payload = {
            "c": channel_name,
            "t": ts_ns,
            "v": serialized_value
        }
        
        encoded_payload = _msgpack_packb(payload, use_bin_type=True)
        if encoded_payload is None:
            raise ValueError("msgpack encoding failed")
        
        frame_len = 4 + len(encoded_payload)
        
        with self._lock:
            chunk_size_bytes = self.config["chunk_size_mb"] * 1024 * 1024
            if self._log_file is not None and self._current_log_size + frame_len > chunk_size_bytes:
                self._rotate_log_file()

            if self._log_file is None:
                self._log_file = open(self.run_path / "log.bin", "ab")
                self._current_log_size = 0
            
            # 4-byte uint32 little-endian length prefix
            header = _pack_uint32(len(encoded_payload))
            self._log_file.write(header)
            self._log_file.write(encoded_payload)
            self._log_file.flush()
            self._current_log_size += frame_len

    def _rotate_log_file(self):
        if self._log_file:
            self._log_file.close()
            self._log_file = None
            
        src = self.run_path / "log.bin"
        if src.exists():
            dest = self.run_path / "chunks" / f"{self._log_file_count:04d}.bin"
            shutil.move(str(src), str(dest))
            self._log_file_count += 1
            self._current_log_size = 0

    def sync(self):
        """User-triggered explicit sync."""
        self._sync_internal()

    def _sync_internal(self):
        """Internal sync logic used by both user and background thread."""
        with self._lock:
            # Only rotate if there's actual data to rotate
            if self._current_log_size > 0:
                self._rotate_log_file()
        
        # sync_pending handles the actual upload and can be called outside the lock
        # as ChunkSyncer has its own locking for network/state operations.
        self._syncer.sync_pending()

    def complete(self, status: str = "complete"):
        with self._lock:
            if self._log_file:
                self._log_file.close()
                self._log_file = None
            self._rotate_log_file()

        if self._bg_sync is not None:
            self._bg_sync.stop()
            self._bg_sync = None

        self._syncer.sync_pending()

        final_chunk_idx = self._log_file_count - 1  # _log_file_count is next idx, so -1 is last

        if status == "complete":
            res = self._syncer.complete(final_chunk_idx)
            if res:
                # Success! Delete local cache
                try:
                    if self._lock_file_path.exists():
                        self._lock_file_path.unlink()
                    shutil.rmtree(self.run_path)
                except Exception as e:
                    warnings.warn(f"Failed to cleanup cache directory: {e}")
            return res
        else:
            # For abort or incomplete, we don't necessarily delete the cache 
            # unless we want to discard it.
            if self._lock_file_path.exists():
                self._lock_file_path.unlink()
            return None

    def abort(self, reason: str = "user_abort"):
        """Abort the current run on the server."""
        url = f"https://{self.server}/runs/{self.run_id}/abort"
        try:
            requests.post(url, json={"reason": reason}, timeout=2.0, verify=self.ssl_verify)
        except Exception as e:
            warnings.warn(f"Failed to send abort to server: {e}")
        self.complete(status="aborted")

    def _generate_short_uuid(self) -> str:
        u = uuid.uuid4()
        short = base64.urlsafe_b64encode(u.bytes).decode('utf-8')
        return short.rstrip('=')
    
    def _get_version(self) -> str:
        try:
            return version("lab-log")
        except PackageNotFoundError:
            return "0.0.0-dev"

    def _generate_manifest(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "experiment_id": self.experiment_id,
            "trial_name": self.trial_name,
            "trial_number": self.trial_number,
            "researcher": self.researcher,
            "hostname": self.hostname,
            "timestamp_start_utc": self.timestamp_start.isoformat(timespec='seconds').replace("+00:00", "Z"),
            "lab_log_version": self._get_version(),
            "server": self.server,
            "non_loggable_params": self.config["non_loggable_params"],
            "declared_channels": [ch.to_dict() for ch in self.channels.values()]
        }
