import struct
import json
import time
import threading
import warnings
import shutil
from datetime import datetime, timezone
from typing import Any, Optional, Callable, Dict, List
from pathlib import Path
import msgpack
import uuid
import base64
import requests
from importlib.metadata import version, PackageNotFoundError

from .channel import ChannelDef
from .serialize import get_or_make_handler
from .serialize import resolve_value

# function localization for commonly used paths
_pack_uint32 = struct.Struct("<I").pack
_msgpack_packb = msgpack.packb
_time_ns = time.time_ns

class LabLog:
    trial_name: str # name of trial
    experiment_id: str # grouping for trial
    researcher: str # person running trial
    hostname: str # machine name
    server: str # server, wip
    run_id: str # unique id for this run, generated by client
    run_path: Path
    channels: Dict[str, ChannelDef]
    # channel tiers
    # 1. float, int, ndarray, Tensor
    # 2. string, dict, list, model weights
    # 3. JSON version of a device.
    config: Dict[str, Any]
    _lock: threading.Lock
    _log_file: Optional[Any] = None
    _log_file_count: int = 0
    _current_log_size: int = 0
    
    timestamp_start: datetime # all times in utc
            
    def __init__(self, 
                 trial_name: str, 
                 experiment_id: str, 
                 researcher: str = "", 
                 hostname: str = "", 
                 server: str = "localhost:36524",
                 cache_dir: str = "~/.lablog/cache"):
        self.trial_name = trial_name
        self.experiment_id = experiment_id
        self.researcher = researcher
        self.hostname = hostname
        self.server = server
        self.run_id = self._generate_short_uuid()
        self.timestamp_start = datetime.now(timezone.utc)
        self.channels = {}
        self._lock = threading.Lock()
        self._log_file_count = 0
        self._current_log_size = 0
        
        self.config = {
            "sync_interval": 60,
            "chunk_size_mb": 32,
            "non_loggable_params": {},
            "cache_dir": cache_dir
        }

        # cache_dir/<experiment_id>/<run_id>/
        self.run_path = Path(self.config["cache_dir"]).expanduser() / self.experiment_id / self.run_id
        self.run_path.mkdir(parents=True, exist_ok=True)
        (self.run_path / "chunks").mkdir(exist_ok=True)

        self._write_manifest() # save manifest
        self._send_manifest()   # try to send to server

    def _send_manifest(self):
        url = f"http://{self.server}/runs"
        try:
            response = requests.post(url, json=self._generate_manifest(), timeout=2.0)
            if response.status_code == 200:
                data = response.json()
                # If server returns a trial_number, we can update it locally if needed
                #TODO Future: update local manifest with server response)
                pass
            else:
                warnings.warn(f"Server rejected manifest with status {response.status_code}. Continuing locally.")
        except Exception as e:
            warnings.warn(f"Failed to reach server {self.server}: {e}. Continuing locally.")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        status = "complete" if exc_type is None else "incomplete"
        self.complete(status=status)

    def configure(self, 
                  sync_interval: Optional[int] = None, 
                  chunk_size_mb: Optional[float] = None, 
                  non_loggable_params: Optional[dict] = None, 
                  server: Optional[str] = None):
        
        if sync_interval is not None: self.config["sync_interval"] = sync_interval
        if chunk_size_mb is not None: self.config["chunk_size_mb"] = chunk_size_mb
        if non_loggable_params is not None: self.config["non_loggable_params"] = non_loggable_params
        if server is not None: self.server = server
        
        self._write_manifest()

    def _write_manifest(self):
        manifest_path = self.run_path / "manifest.json"
        with open(manifest_path, "w") as f:
            json.dump(self._generate_manifest(), f, indent=2)

    def declare_channel(self, 
                        name: str, 
                        dtype: str, 
                        shape: Optional[List[Optional[int]]] = None, 
                        unit: Optional[str] = None,
                        description: Optional[str] = None,
                        compression: str = "gzip",
                        compression_level: int = 4,
                        frequency_hz: Optional[float] = None,
                        serializer: Optional[Callable[[Any], Any]] = None,
                        pickle: bool = False):
        
        ch = ChannelDef(
            name=name,
            dtype=dtype,
            shape=shape,
            unit=unit,
            description=description,
            compression=compression,
            compression_level=compression_level,
            frequency_hz=frequency_hz,
            serializer=serializer,
            pickle=pickle
        )
        ch.validate()
        self.channels[name] = ch
        self._write_manifest()

    def log(self, channel_name: str, value: Any, timestamp: Optional[int] = None):
        # now using hashtable, much faster lookups.
        ch = self.channels.get(channel_name)
        if ch is None:
            warnings.warn(f"Ad-hoc logging to undeclared channel '{channel_name}'")
            resolved_dtype, _ = resolve_value(None, value)
            ch = ChannelDef(name=channel_name, dtype=resolved_dtype)
            self.channels[channel_name] = ch
            self._write_manifest()

        # save used handler
        if ch._cached_handler is None:
            ch._cached_handler = get_or_make_handler(ch, value)
        
        ts_ns = timestamp if timestamp is not None else _time_ns()
        
        _, serialized_value = ch._cached_handler(value)
        
        payload = {
            "c": channel_name,
            "t": ts_ns,
            "v": serialized_value
        }
        
        encoded_payload = _msgpack_packb(payload, use_bin_type=True)
        if encoded_payload is None:
            raise ValueError("msgpack encoding failed")
        
        frame_len = 4 + len(encoded_payload)
        
        with self._lock:
            chunk_size_bytes = self.config["chunk_size_mb"] * 1024 * 1024
            if self._log_file is not None and self._current_log_size + frame_len > chunk_size_bytes:
                self._rotate_log_file()

            if self._log_file is None:
                self._log_file = open(self.run_path / "log.bin", "ab")
                self._current_log_size = 0
            
            # 4-byte uint32 little-endian length prefix
            header = _pack_uint32(len(encoded_payload))
            self._log_file.write(header)
            self._log_file.write(encoded_payload)
            self._log_file.flush()
            self._current_log_size += frame_len

    def _rotate_log_file(self):
        if self._log_file:
            self._log_file.close()
            self._log_file = None
            
        src = self.run_path / "log.bin"
        if src.exists():
            dest = self.run_path / "chunks" / f"{self._log_file_count:04d}.bin"
            shutil.move(str(src), str(dest))
            self._log_file_count += 1
            self._current_log_size = 0

    def sync(self):
        #TODO Background sync
        pass

    def complete(self, status: str = "complete"):
        with self._lock:
            if self._log_file:
                self._log_file.close()
                self._log_file = None

            self._rotate_log_file()
            
            #TODO finalize completion for server
            pass
        pass

    def _generate_short_uuid(self) -> str:
        u = uuid.uuid4()
        short = base64.urlsafe_b64encode(u.bytes).decode('utf-8')
        return short.rstrip('=')
    
    def _get_version(self) -> str:
        try:
            return version("lab-log")
        except PackageNotFoundError:
            return "0.0.0-dev"

    def _generate_manifest(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "experiment_id": self.experiment_id,
            "trial_name": self.trial_name,
            "researcher": self.researcher,
            "hostname": self.hostname,
            "timestamp_start_utc": self.timestamp_start.isoformat(timespec='seconds').replace("+00:00", "Z"),
            "lab_log_version": self._get_version(),
            "server": self.server,
            "non_loggable_params": self.config["non_loggable_params"],
            "declared_channels": [ch.to_dict() for ch in self.channels.values()]
        }
