import struct
import json
import time
import threading
import warnings
from datetime import datetime, timezone
from typing import Any, Optional, Callable, Dict, List
from pathlib import Path
import msgpack
import uuid
import base64
from importlib.metadata import version, PackageNotFoundError

from .channel import ChannelDef
from .serialize import resolve_value

class LabLog:
    trial_name: str # name of trial
    experiment_id: str # grouping for trial
    researcher: str # person running trial
    hostname: str # machine name
    server: str # server, wip
    run_id: str # unique id for this run, generated by client
    run_path: Path
    channels: Dict[str, ChannelDef]
    # channel tiers
    # 1. float, int, ndarray, Tensor
    # 2. string, dict, list, model weights
    # 3. JSON version of a device.
    config: Dict[str, Any]
    _lock: threading.Lock
    _log_file: Optional[Any] = None
    
    timestamp_start: datetime # all times in utc
            
    def __init__(self, 
                 trial_name: str, 
                 experiment_id: str, 
                 researcher: str = "", 
                 hostname: str = "", 
                 server: str = "localhost:36524",
                 cache_dir: str = "~/.lablog/cache"):
        self.trial_name = trial_name
        self.experiment_id = experiment_id
        self.researcher = researcher
        self.hostname = hostname
        self.server = server
        self.run_id = self._generate_short_uuid()
        self.timestamp_start = datetime.now(timezone.utc)
        self.channels = {}
        self._lock = threading.Lock()
        
        self.config = {
            "sync_interval": 60,
            "chunk_size_mb": 10,
            "non_loggable_params": {},
            "cache_dir": cache_dir
        }

        # cache_dir/<experiment_id>/<run_id>/
        self.run_path = Path(self.config["cache_dir"]).expanduser() / self.experiment_id / self.run_id
        self.run_path.mkdir(parents=True, exist_ok=True)

        self._write_manifest() # save manifest

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        status = "complete" if exc_type is None else "incomplete"
        self.complete(status=status)

    def configure(self, 
                  sync_interval: Optional[int] = None, 
                  chunk_size_mb: Optional[int] = None, 
                  non_loggable_params: Optional[dict] = None, 
                  server: Optional[str] = None):
        
        if sync_interval is not None: self.config["sync_interval"] = sync_interval
        if chunk_size_mb is not None: self.config["chunk_size_mb"] = chunk_size_mb
        if non_loggable_params is not None: self.config["non_loggable_params"] = non_loggable_params
        if server is not None: self.server = server
        
        self._write_manifest()

    def _write_manifest(self):
        manifest_path = self.run_path / "manifest.json"
        with open(manifest_path, "w") as f:
            json.dump(self._generate_manifest(), f, indent=2)

    def declare_channel(self, 
                        name: str, 
                        dtype: str, 
                        shape: Optional[List[Optional[int]]] = None, 
                        unit: Optional[str] = None,
                        description: Optional[str] = None,
                        compression: str = "gzip",
                        compression_level: int = 4,
                        frequency_hz: Optional[float] = None,
                        serializer: Optional[Callable[[Any], Any]] = None,
                        pickle: bool = False):
        
        ch = ChannelDef(
            name=name,
            dtype=dtype,
            shape=shape,
            unit=unit,
            description=description,
            compression=compression,
            compression_level=compression_level,
            frequency_hz=frequency_hz,
            serializer=serializer,
            pickle=pickle
        )
        ch.validate()
        self.channels[name] = ch
        self._write_manifest()

    def log(self, channel_name: str, value: Any, timestamp: Optional[int] = None):
        ch = self.channels.get(channel_name)
        if ch is None:
            warnings.warn(f"Ad-hoc logging to undeclared channel '{channel_name}'")
            # auto_detection script, useful for dynamically declared variables. 
            # suppress warnings if used frequently.
            resolved_dtype, _ = resolve_value(None, value)
            ch = ChannelDef(name=channel_name, dtype=resolved_dtype)
            self.channels[channel_name] = ch
            self._write_manifest()
        
        ts_ns = timestamp if timestamp is not None else time.time_ns()
        
        # serialize value according to dtype and Tier rules
        resolved_dtype, serialized_value = resolve_value(ch, value)
        
        payload = {
            "c": channel_name,
            "t": ts_ns,
            "v": serialized_value
        }
        
        # packing with msgpack
        encoded_payload = msgpack.packb(payload, use_bin_type=True)
        
        with self._lock:
            if self._log_file is None:
                self._log_file = open(self.run_path / "log.bin", "ab")
   
            if encoded_payload is None:
                raise ValueError("Encoded payload is None, cannot write to log.")
            header = struct.pack("<I", len(encoded_payload))
            self._log_file.write(header)
            self._log_file.write(encoded_payload)
            self._log_file.flush()

    def sync(self):
        #TODO Background sync
        pass

    def complete(self, status: str = "complete"):
        with self._lock:
            if self._log_file:
                self._log_file.close()
                self._log_file = None
        
        #TODO finalize completion for server
        pass

    def _generate_short_uuid(self) -> str:
        u = uuid.uuid4()
        short = base64.urlsafe_b64encode(u.bytes).decode('utf-8')
        return short.rstrip('=')
    
    def _get_version(self) -> str:
        try:
            return version("lab-log")
        except PackageNotFoundError:
            return "0.0.0-dev"

    def _generate_manifest(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "experiment_id": self.experiment_id,
            "trial_name": self.trial_name,
            "researcher": self.researcher,
            "hostname": self.hostname,
            "timestamp_start_utc": self.timestamp_start.isoformat(timespec='seconds').replace("+00:00", "Z"),
            "lab_log_version": self._get_version(),
            "server": self.server,
            "non_loggable_params": self.config["non_loggable_params"],
            "declared_channels": {name: ch.to_dict() for name, ch in self.channels.items()}
        }
